### PR TITLE
Some very careful edits

### PR DESCRIPTION
**Pull request by iclnmh**

### CODE REVIEW

**Comment by iclnmh** [comment]
seas

**Comment by bcamino** [comment]
Thank you for the pull request. It looks all good. I am going to merge the pull request.

Bruno

**Comment by iclnmh** [comment]
Hi Bruno - this all made sense. Very much like CVS in the very old days in fact.
Do you have any experience of GitHub desktop. It looks quite useful although I find the command line better at the moment.

**Comment by bcamino** [comment]
I'm glad to hear that and thank you for the edits in the Google Drive. I don't have any GitHub Desktop experience. I think the command line is quite useful. Rather than using the Desktop one, I would probably use the integration with MS Visual Sudio or Atom.

**Pull request merged**
